language: node_js

services:
  - postgresql

node_js:
  - '8'
  - '10'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

cache:
  yarn: true
  directories:
    - 'node_modules'

before_script:
  - psql -c 'CREATE DATABASE "test";' -U postgres

script:
  - yarn lint
  - yarn build
  - yarn test

after_success: yarn cover

notifications:
  email: never

stages:
  - test
  - name: deploy
    if: type = push AND tag IS present AND branch = master

jobs:
  include:
    - stage: deploy
      node_js: '10'
      script:
        - yarn build
      before_deploy:
        - cd dist
      deploy:
        skip_cleanup: true
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          tags: true
